### ISSUE TITLE
Loading OBJ crashes UE

### ISSUE THREAD

**Issue by SolarCookies** [getnamo/RuntimeGeometryUtils#1]
When exporting to obj with DynamicMeshOBJWriter I cant import it back with import mesh and blender cant import the obj. Ive attached the obj that it output. However you can import the obj into blender if you turn on keep vert order.
[1.zip](https://github.com/getnamo/RuntimeGeometryUtils/files/7965118/1.zip)
.

**Comment by getnamo** [comment]
Your best bet would be to open the issue on https://github.com/gradientspace/UnrealRuntimeToolsFrameworkDemo as that part is written by gradientspace.
